doc.type.html
html lang en 
script
header=document create.element(header)
header.style.backgroundcolor=#4caf50
header.style.color=’white’
header.style.padding=’10px’
header.style.textalign=’center’
header.style.text.fontsize=’24px’
header.textcontent=’welcome to covid strings15’
document appendchild(header)
<header.html>
heading variables 
the heading numbers that determine where each heading and subheading go
heading1=game code overview
heading2=background functions
heading3=game code part1
heading4=phrases
heading5=multiple choice questions
heading6=math problems
heading7=sentences
heading8=game code part2 
heading9=answer checker
heading10=winner checker
subheading1=polling problems
subheading2=answer scanner
filename=covidstrings15.js
<header.html>
game code overview
an outline of the game code for covid strings15
java.awt.graphics
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
div id=header></div
audio=new audio(audio_file mp3)
audio.play 
random button
new button (set random color)
option button
new  button (change color)
public fun with graphics()
color panel
add (panel,center )
button panel
new  panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r= newrandom();
<header.html>
background functions
the functions that lead into the background that are the first things the user will experience
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),))
num teams
total players=players per team
if players per team=zero
return zero
else 
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
<header.html>
game code part1
part1 of game code for covid strings15(value object[team-color]-desired color green)
public actionperformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static void main(string [] args)
jframe f = new covid strings15()
f.set title(covid strings15)
f.set default closeoperation(exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult ==x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult ==x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblScore=document.getelementbyid(lblscore)
lbl.score.inner html=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object[team color]
covidstrings teamlist15= [turquoise waves,green peacemakers,white transit angels,magenta magnetizers,red protein spikers,yellow moxie,purple brave hearts,burgundy rebuilders]
<header.html>
phrases
phrases that involve both non-concatenated and concatenated strings
covidstringsphraselist15=[ non-concatenated strings "trumps about face on covid is particularly offensive to people dealing with the worst impacts of long covid"
"chinas newest mystery pathogen might prove even worse"
"this is even after seventy six days of lockdowns account of covid in wuhan"
"at least there are plenty of covid songs to help alleviate the pain"
"the gryphon variant is another example of the changing dynamics of covid"
"one thing that is not surprising is that chinas reopening post covid is fake"
"whats definitely real is rihannas song work being a work from home song"
"another real song is luke combs' six feet apart"
concatenated strings
"getting"+"fully"+"vaccinated"+"is"+"even"+"more"+"real"+"than"+"working"+"from"+"home"
"this"+"is"+"especially"+"true"+"considering"+"that"+"a"+"new"+"study"+"says"+"covid"+"is"+"deadlier"+"than"+"flu"
"it"+"is"+"then"+"even"+"more"+"concerning"+"that"+"china"+"has"+"been"+"censoring"+"the"+"fact"+"that"+"it"+"had"+"a"+"zero"+"covid"+"policy"
"luckily"+"a"+"vaccine"+"that"+"kills"+"covid"+"and"+"flu"+"might"+"be"+"coming"+"soon"
"economically"+"covid"+"was"+"another"+"instance"+"of"+"boomers"+"winning"+"and"+"xers"+"suffering"
"this"+"is"+"less"+"concerning"+"than"+"if"+"covid"+"morphs"+"into"+"a"+"stomach"+"bug"
"luckily"+"disposable"+"masks"+"can"+"still"+"offer"+"some"+"protection"
"jn1"+"provides"+"a"+"potential"+"challenge"+"to"+"vaccines"]
string manager{non-concatenated}
insert string (entity,string)
entity.element.text=string
string manager insert string
string manager{concatenated}
insert string (entity,string)
entity.element.text=string
string manager insert string
string=””
for string in covid strings phrase list15 
select characters
edit diffuse property
desired color=green
<header.html>
multiple choice questions 
multiple choice questions and answers that will appear in covid strings15
covidstrings15multiplechoicelist=[1 a charming b offensive c a reminder of his previous statements d angelic, 2 a imaginary b tangible c real d make-believe, 3 a covid songs b rudy giuliani jokes c birds arent real conspiracy theories d rick steves specials, 4 a chinas b the dominican republic  c sri lankas  d malaysia,5 a the same b lighter c deadlier d less fatal , 6 a graphite b graphene c gryphon  d chataswamy,
7a trumps putin love affair b covid and flu c rabies d nuclear fusion, 8 a chinas b papa new guinea c malaysia d indonesias 9 a boomers b millennials c gen zers  d i geners,10 a 2022 blizzard b 2nd coronavirus pandemic c stomach bug d 2023 blizzard
11 a wipes b masks c republican house majorities d armed missionaries, 12 a work b push it c lula says putin will be arrested d trump has one more polling problem,12 a total presidential immunity b vaccines c sam alitos willful blindness doctrine d kamala harris being a liability
13 a dolly parton b ava max c luke combs d the zach brown band, 14 a full of independents b an unlucky generation c like trumps2024 d chinese women 15a melody b harmony  c timbre d trump dictatorship scare
16 a metrics b financial loop c politics d transition, 17 a guesswork b an exact science c a war of narratives d something to be careful what you ask for, 18 a working from home b trying not to get elected c an unprecedented danger to democracy d losers bets,
19,a yes b no 
<header.html>
math problems
covid related math problems that will appear in covid strings15
covid strings15mathproblemlist =[ non-concatenated strings  "if53 percent viewed six feet apart as the best pandemic song how many dont"?,"if the margin of error is 6 percent what is the range"?,"if the margin of error is 6 percent what is the range"?,"if the second place choice is we can work from home with  41 percent what is the difference?”,“given the same margin of error what is the range for we can work from home?”,]
[concatenated strings“if”+”a”+’poll”+”finds”+”that”+”97”+”percent”+”of”+”americans”+”know”+”of”+”at”+”least”+”one”+”covid”+”song”+”how”+”many”+”don’t?”,”if”+”54”+”percent”+”said”+”one”+”song”+”they”+”knew”+”was”+”level”+”of”+”concern”+”how”+”many”+”know”+”something”+”else?”,“of”+”those”+”46”+”percent”+”if”+”60”+”percent”+”said”+”their”+”other”+”song”+”was”+”season”+”of”+”the”+”sticks”+”how”+”many”+”people”+”is”+”that?”,if”+”only”+”34”+”percent”+”of”+”americans”+”believe”+”covid”+”is”+”worse”+”than”+”the”+”flu”+”what”+”is”+”the”+”remaining”+”percent?” ,”if”+”the”+”margin”+”of”+”error”+”is”+”6.5”+”percent”+”what”+”is”+”the”+”range?”,“if”+”56”+”out”+”of”+”the”+”66”+”percent”+”say”+”their”+”reason”+”was”+”because”+”the”+”vaccines”+”made”+”covid”+”milder”+”what”+”percent”+”don’t?”]
string manager{non-concatenated}
insert string (entity,string)
entity.element.text=string
string manager insert string
string manager{concatenated}
insert string (entity,string)
entity.element.text=string
string manager insert string
string=””
for string in covid strings15 math problems list 
select characters
edit diffuse property
desired color=green
public static main(String [] Args)
int number
number=number*2
system.out print in (“the number is“ +number)
<subheading.html>
polling problems
math problems that involve the use of polls
polling function (exact,number)
console log (exact:${exact}, number:${number},
if polling function log== (exact,number)
return true
else:
return false
if polling function log==(number,exact)
return false
else:
return true  
for math problems in covid strings math problem list 
if math problem==polling percent:
subtract exact from100
else:
remain 
if math problem==margin of error:
add and subtract exact number
else:
remain 
<header.html>
sentences
covid related sentences that will appear in covid strings15
covid strings sentencelist15=["rihanna could certainly provide a fifth harmony to work from home","six feet apart should not be interpreted as a statement on how americas covid metrics differ from the rest of the world","getting fully vaccinated and working from home are equally progressive in their own right”, “covid”+”proves”+”that”+”gen”+”x”+”is”+”an”+”unlucky”+”generation”,“the”+”marign”+”of”+”error”+”for”+”covid”+”song”+”polling”+”is”+”guesswork” ]
string manager{non-concatenated}
insert string (entity,string)
entity.element.text=string
string manager insert string
string manager{concatenated}
insert string (entity,string)
entity.element.text=string
string manager insert string
string=””
for string in covid strings sentence list15 
select characters
edit diffuse property
desired color=green
<header.html>
game code part2
the rest of the game code excluding answer and winner checker
java util.scanner
java.util
questions=total# of questions from covid strings15 [first-championship round]
collections.shuffle(arrays.aslist(questions)
userin.select team
import meta.
class myclass
constructor(non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else:
prompt 
log
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else:
prompt 
log
import syntax 
substring(start,end)
<header.html>
answer checker
the feature within covid strings that allows the software to check whether a users answer is correct
for multiple choice questions in covid strings 
if selectedanswer==correct answer:
return true
else:
return false
if selectedanswer=not correct
return false
else: 
return true
for math problems in covid strings
if typed answer == correct
return true
else:
return false
if typed answer== not correct
return false
else
return true
public static main(string []args)
int number
number=number*2
system.out print in (“the number is“ +number)
<subheading.html>
answer scanner
the feature within the covid strings answer checker that allows for confirmation of the user 
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.n=nextline()
if useranswer.equals(correctanswer)
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
<header.html>
winner checker
the feature within covid strings that allows for the player to know if their team won 
check winner:
if winner==true:
log(the winner is)
else:
remain
if winner==false:
log(no winner yet) 
else:
log winner
if users team wins covid strings15 
console log users team wins covid strings15 
else:
remain
if users team loses covid strings15
return game over
else:
remain
return filename




