doc.type html
script
html
head
utf8
viewport content=width=device-width, initial-scale=one>
title covidstrings 15 first round bracket
viewportcontent=width=device-width, initial-scale=one>
title covid strings15 first round
filename=covid strings15 first round.js
firstround=(highest overall seed ,second highest seed third highest seed first middle seed, second middle seed,  third lowest seed ,second lowest seed,lowest overall seed)
highest overall seed = 1 seed
second highest seed=2 seed
third highest seed=3 seed
firstmiddleseed=4seed
second middle seed = 5 seed
third lowest seed= 6 seed
second lowest seed = 7 seed
lowest overall seed = 8 seed
covidstringsteamlist15=[turquoise,green,white,magenta,red,yellow,purple, burgundy]
create matchup(yellow versus white)
create matchup(purple versus green)
create matchup(magenta versus red)
create matchup(burgundy versus turquoise)
bracket =getelementbyid(bracket);
document.createelement 
matchupdiv.classname=(matchup)
matchupdiv.innerHTML =[matchup]
rounddiv.appendchild(matchup)
for (i in covid strings first round)
round div=create element
round div class name=covid strings15 first round
bracket.appendchild(round div)
if (event.target.covid strings seed list.contains(matchup))
event.target.covid strings seed list.toggle
else:
addmatchup
java util.scanner
java.util
questions[]questions={
question1
question2
question3
question4
question5
question6
question7
question8
question9
question10
question11
question12
question13
question14
question15
if selectedanswer==correct:
return true
else:
return false
advancingteam=slice(current teams)
declarewinner
let result=declarewinner(team1 score, team2 score)
if white score>=forty:
console.log(white transit angels win)
else:
console.log(yellow moxie wins)
if green score>=forty:
console.log(green peacemakers win)
else:
console.log(purple bravehearts win)
if red score>forty:
console.log(red protein spikers win)
else:
console.log(magenta magentizers win)
if turquoise score>forty:
console.log(turquoise waves win)
else:
console.log(burgundy rebuilders win)
return filename

